- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      args: ["-q", "-r", "."]
      exclude: |
        (?x)(
          ^\.venv/|
          ^venv/|
          ^env/|
          ^output/
        )
