repos:
  - repo: local
    hooks:
      - id: validate-roadmap
        name: Validate Roadmap Report
        entry: python3 scripts/validate_report.py --input output/roadmap_report.md --check-deep-dive
        language: system
        pass_filenames: false
