- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks:
    - id: bandit
      name: bandit (repo sources only)
      args:
        - -q
        - -r
        - scripts
        - tests
        - --severity-level
        - HIGH
        - --confidence-level
        - HIGH
      exclude: >
        (?x)(
          ^\.venv/|
          ^env/|
          ^venv/|
          ^output/|
          ^\.git/|
          .*/site-packages/|
          ^build/|
          ^dist/
        )
      pass_filenames: false
