[tool.ruff]
line-length = 100
target-version = "py311"
lint.select = ["E","W","F","I","UP","N","B","A","C4","PT","SIM","ARG","T20","ERA","DTZ"]
lint.ignore = ["E203"]
lint.exclude = ["output"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
disallow_untyped_defs = true
no_implicit_optional = true
check_untyped_defs = true
exclude = ["output/"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]

[tool.coverage.run]
branch = true
source = ["."]
omit = ["*/tests/*", "output/*"]

[tool.bandit]
skips = ["B101"]
