name: _Roadmap Smoke

on:
  workflow_dispatch:
    inputs:
      msg:
        description: Message to print
        required: false
        default: hello

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF"
          echo "Msg:  ${{ github.event.inputs.msg }}"
