
name: data
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"  # daily 09:00 UTC

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # minimal extras in case not present
          pip install requests beautifulsoup4 msal plotly streamlit pandas

      - name: Generate data
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python -m scripts.cli.generate_report --mode auto

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: output/

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload static HTML to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/roadmap_report.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
