name: Generate Microsoft 365 Roadmap Report

on:
  workflow_dispatch:
    inputs:
      skip_generate:
        description: "Skip API generation and use sample file (first-run safe)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]
      test_discovery:
        description: "Discovery Test Mode: only fetch IDs and upload CSV (no report generation)"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]
      ids:
        description: "Comma-separated Roadmap IDs (leave blank to auto-discover by filters)"
        required: false
        default: ""
      report_title:
        description: "Title for output files (no spaces)"
        required: false
        default: "roadmap_report"
      model:
        description: "OpenAI model (default: gpt-4o; you can override to gpt-5)"
        required: false
        default: "gpt-4o"
      months:
        description: "Months back from today to include (1..6) OR leave blank to use since/until"
        required: false
        default: "3"
      since:
        description: "Start date (YYYY-MM-DD). If set and 'until' blank, defaults to +6 months."
        required: false
        default: ""
      until:
        description: "End date (YYYY-MM-DD)"
        required: false
        default: ""
      include_instances:
        description: "Include Cloud Instances (e.g., DoD,GCC,GCC High,Worldwide (Standard Multi-Tenant))"
        required: false
        default: ""
      exclude_instances:
        description: "Exclude Cloud Instances (comma-separated)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements (if requirements.txt exists)
        shell: bash
        run: |
          set -euxo pipefail
          if [[ -f requirements.txt ]]; then
            python -m pip install --upgrade pip wheel
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping pip install."
          fi

      - name: Make scripts executable & normalize line endings
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update && sudo apt-get install -y dos2unix
          if compgen -G "scripts/*.sh" > /dev/null; then dos2unix scripts/*.sh || true; chmod +x scripts/*.sh; fi
          if [[ -f scripts/fetch_ids.py ]]; then dos2unix scripts/fetch_ids.py || true; chmod +x scripts/fetch_ids.py; fi
          if [[ -f scripts/write_sample.sh ]]; then dos2unix scripts/write_sample.sh || true; chmod +x scripts/write_sample.sh; fi

      - name: Ensure sample report exists (first-run safety)
        shell: bash
        env:
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
        run: |
          set -euxo pipefail
          mkdir -p output
          if [[ ! -f "output/${TITLE}.md" ]]; then
            bash scripts/write_sample.sh "output/${TITLE}.md"
          else
            echo "Sample already present at output/${TITLE}.md; skipping."
          fi

      - name: Auto-discover Roadmap IDs (multi-pass, never hard-fails)
        if: ${{ github.event.inputs.skip_generate == 'false' && (github.event.inputs.ids == '' || github.event.inputs.ids == null) }}
        id: discover
        shell: bash
        env:
          MONTHS: ${{ github.event.inputs.months }}
          SINCE: ${{ github.event.inputs.since }}
          UNTIL: ${{ github.event.inputs.until }}
          INCLUDE: ${{ github.event.inputs.include_instances }}
          EXCLUDE: ${{ github.event.inputs.exclude_instances }}
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
        run: |
          set -euo pipefail
          mkdir -p output

          run_discovery () {
            local months="$1" since="$2" until="$3" include="$4" exclude="$5" outfmt="$6"
            python scripts/fetch_ids.py \
              --months "${months}" \
              --since "${since}" \
              --until "${until}" \
              --include "${include}" \
              --exclude "${exclude}" \
              --max-pages 30 \
              --emit "${outfmt}"
          }

          echo "Pass A: Using provided filters (months='${MONTHS}', since='${SINCE}', until='${UNTIL}', include='${INCLUDE}', exclude='${EXCLUDE}')"
          IDS="$(run_discovery "${MONTHS:-}" "${SINCE:-}" "${UNTIL:-}" "${INCLUDE:-}" "${EXCLUDE:-}" list || true)"
          echo "Pass A discovered IDs: ${IDS}"

          if [[ -z "${IDS}" ]]; then
            echo "Pass B: Dropping instance filter (include='')"
            IDS="$(run_discovery "${MONTHS:-}" "${SINCE:-}" "${UNTIL:-}" "" "${EXCLUDE:-}" list || true)"
            echo "Pass B discovered IDs: ${IDS}"
          fi

          if [[ -z "${IDS}" ]]; then
            echo "Pass C: Dropping date filters too (months='', since='', until='')"
            IDS="$(run_discovery "" "" "" "" "${EXCLUDE:-}" list || true)"
            echo "Pass C discovered IDs: ${IDS}"
          fi

          # Always emit a CSV of what we found in the last pass
          echo "Writing discovery CSV..."
          run_discovery "" "" "" "" "${EXCLUDE:-}" csv > "output/${TITLE}_discovered_ids.csv" || true

          if [[ -n "${IDS}" ]]; then
            echo "ids=${IDS}" >> "$GITHUB_OUTPUT"
            echo "✅ Discovery succeeded with one of the passes."
          else
            echo "⚠️ Discovery could not find IDs. You can still download the discovery CSV artifact to inspect."
            # Set an explicit empty output so downstream can skip generation.
            echo "ids=" >> "$GITHUB_OUTPUT"
          fi

      - name: Upload discovery CSV (when in test mode)
        if: ${{ github.event.inputs.skip_generate == 'false' && github.event.inputs.test_discovery == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-discovery
          path: output/${{ github.event.inputs.report_title || 'roadmap_report' }}_discovered_ids.csv
          if-no-files-found: warn

      - name: Generate Markdown report via API (only if we have IDs)
        if: ${{ github.event.inputs.skip_generate == 'false' && github.event.inputs.test_discovery != 'true' }}
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL: ${{ github.event.inputs.model || 'gpt-4o' }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
        run: |
          set -euo pipefail
          if [[ -z "${OPENAI_API_KEY:-}" ]]; then
            echo "Missing OPENAI_API_KEY secret. Set it in Settings → Secrets → Actions." >&2
            exit 1
          fi

          RAW_IDS="${{ github.event.inputs.ids }}"
          if [[ -z "$RAW_IDS" ]]; then
            RAW_IDS="${{ steps.discover.outputs.ids }}"
          fi

          if [[ -z "$RAW_IDS" ]]; then
            echo "ℹ️ No IDs to generate a report from (discovery found none and no ids were provided). Skipping generation."
            exit 0
          fi

          TITLE="${{ github.event.inputs.report_title || 'roadmap_report' }}"
          mkdir -p output
          echo "Using IDs: $RAW_IDS"
          bash scripts/generate_report.sh "$RAW_IDS" "prompts/system_multi_id.md" "output/${TITLE}.md"
      - name: Post-process to CSV/JSON (always runs)
        shell: bash
        env:
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
          MONTHS: ${{ github.event.inputs.months }}
          SINCE: ${{ github.event.inputs.since }}
          UNTIL: ${{ github.event.inputs.until }}
          INCLUDE: ${{ github.event.inputs.include_instances }}
          EXCLUDE: ${{ github.event.inputs.exclude_instances }}
        run: |
          set -euxo pipefail
          bash scripts/post_process.sh \
            "output/${TITLE}.md" \
            "output/${TITLE}.csv" \
            "output/${TITLE}.json" \
            "${MONTHS}" "${SINCE}" "${UNTIL}" "${INCLUDE}" "${EXCLUDE}"

      - name: Show output directory (debug)
        shell: bash
        run: |
          set -euxo pipefail
          echo "Listing output/"
          ls -la output || true

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-report
          path: |
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.md
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.csv
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.json
            output/*
          if-no-files-found: warn
