name: Generate Microsoft 365 Roadmap Report

on:
  workflow_dispatch:
    inputs:
      ids:
        description: "Comma-separated list of Roadmap IDs"
        required: true
      report_title:
        description: "Title for the output files (no spaces)"
        default: "roadmap_report"
        required: false
      model:
        description: "OpenAI model to use (defaults to gpt-4o)"
        default: "gpt-4o"
        required: false
      months:
        description: "Number of months forward from now to include"
        default: "3"
        required: false
      since:
        description: "Start date in YYYY-MM-DD format"
        required: false
      until:
        description: "End date in YYYY-MM-DD format"
        required: false
      include_instances:
        description: "Comma-separated list of instances to include (e.g. GCC,GCC High,DoD)"
        required: false
      exclude_instances:
        description: "Comma-separated list of instances to exclude"
        required: false

jobs:
  generate-roadmap-report:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Markdown report via API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL: ${{ github.event.inputs.model || 'gpt-4o' }}
          OPENAI_ORG_ID: org-xHwYhKYWevRwhrASZm7eCgXd
        run: |
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "Missing OPENAI_API_KEY secret." >&2
            exit 1
          fi

          IDS="${{ github.event.inputs.ids }}"
          TITLE="${{ github.event.inputs.report_title || 'roadmap_report' }}"

          mkdir -p output

          bash scripts/generate_report.sh \
            "$IDS" \
            "prompts/system_multi_id.md" \
            "output/${TITLE}.md"

      - name: Post-process to CSV/JSON
        run: |
          TITLE="${{ github.event.inputs.report_title || 'roadmap_report' }}"
          MONTHS="${{ github.event.inputs.months }}"
          SINCE="${{ github.event.inputs.since }}"
          UNTIL="${{ github.event.inputs.until }}"
          INCLUDE="${{ github.event.inputs.include_instances }}"
          EXCLUDE="${{ github.event.inputs.exclude_instances }}"

          bash scripts/post_process.sh \
            "output/${TITLE}.md" \
            "output/${TITLE}.csv" \
            "output/${TITLE}.json" \
            "$MONTHS" "$SINCE" "$UNTIL" "$INCLUDE" "$EXCLUDE"

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-report
          path: output/
