name: Generate Microsoft 365 Roadmap Report

on:
  workflow_dispatch:
    inputs:
      skip_generate:
        description: "Skip API generation and use sample file (first-run safe)"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]
      test_discovery:
        description: "Discovery Test Mode: only fetch IDs and upload CSV (no report generation)"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]
      ids:
        description: "Comma-separated Roadmap IDs (leave blank to auto-discover by filters)"
        required: false
        default: ""
      report_title:
        description: "Title for output files (no spaces)"
        required: false
        default: "roadmap_report"
      model:
        description: "OpenAI model (default: gpt-4o; you can override to gpt-5)"
        required: false
        default: "gpt-4o"
      months:
        description: "Months back from today to include (1..6) OR leave blank to use since/until"
        required: false
        default: "3"
      since:
        description: "Start date (YYYY-MM-DD). If set and 'until' blank, defaults to +6 months."
        required: false
        default: ""
      until:
        description: "End date (YYYY-MM-DD)"
        required: false
        default: ""
      include_instances:
        description: "Include Cloud Instances (e.g., DoD,GCC,GCC High,Worldwide (Standard Multi-Tenant))"
        required: false
        default: "GCC"
      exclude_instances:
        description: "Exclude Cloud Instances (comma-separated)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements (if requirements.txt exists)
        shell: bash
        run: |
          set -euxo pipefail
          if [[ -f requirements.txt ]]; then
            python -m pip install --upgrade pip wheel
            pip install -r requirements.txt
          else
            echo "No requirements.txt found. Skipping pip install."
          fi


      - name: Make scripts executable & normalize line endings
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y dos2unix
          dos2unix scripts/*.sh || true
          chmod +x scripts/*.sh
          if [ -f scripts/fetch_ids.py ]; then dos2unix scripts/fetch_ids.py; chmod +x scripts/fetch_ids.py; fi
          if [ -f scripts/write_sample.sh ]; then dos2unix scripts/write_sample.sh; chmod +x scripts/write_sample.sh; fi

      - name: Ensure sample report exists (first-run safety)
        shell: bash
        env:
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
        run: |
          if [ ! -f "output/${TITLE}.md" ]; then
            bash scripts/write_sample.sh "output/${TITLE}.md"
          else
            echo "Sample already present at output/${TITLE}.md; skipping."
          fi

      # --------- DISCOVERY (auto-IDs) ---------
      - name: Auto-discover Roadmap IDs (when ids is blank)
        if: ${{ github.event.inputs.skip_generate == 'false' && (github.event.inputs.ids == '' || github.event.inputs.ids == null) }}
        id: discover
        shell: bash
        env:
          MONTHS: ${{ github.event.inputs.months }}
          SINCE: ${{ github.event.inputs.since }}
          UNTIL: ${{ github.event.inputs.until }}
          INCLUDE: ${{ github.event.inputs.include_instances }}
          EXCLUDE: ${{ github.event.inputs.exclude_instances }}
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
        run: |
          mkdir -p output
          echo "Auto-discovering IDs with filters..."
          IDS=$(python scripts/fetch_ids.py \
            --months "${MONTHS:-}" \
            --since "${SINCE:-}" \
            --until "${UNTIL:-}" \
            --include "${INCLUDE:-}" \
            --exclude "${EXCLUDE:-}" \
            --max-pages 20 \
            --emit list)
          echo "Discovered IDs: $IDS"
          if [ -z "$IDS" ]; then
            echo "❌ No IDs discovered with the given filters." >&2
            exit 1
          fi
          # Also emit a CSV for inspection
          python scripts/fetch_ids.py \
            --months "${MONTHS:-}" \
            --since "${SINCE:-}" \
            --until "${UNTIL:-}" \
            --include "${INCLUDE:-}" \
            --exclude "${EXCLUDE:-}" \
            --max-pages 20 \
            --emit csv > "output/${TITLE}_discovered_ids.csv"
          echo "ids=$IDS" >> $GITHUB_OUTPUT

      - name: Upload discovery CSV (when in test mode)
        if: ${{ github.event.inputs.skip_generate == 'false' && github.event.inputs.test_discovery == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-discovery
          path: output/${{ github.event.inputs.report_title || 'roadmap_report' }}_discovered_ids.csv
          if-no-files-found: warn

      # --------- GENERATE (skips if test_discovery=true) ---------
      - name: Generate Markdown report via API (conditional)
        if: ${{ github.event.inputs.skip_generate == 'false' && github.event.inputs.test_discovery != 'true' }}
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL: ${{ github.event.inputs.model || 'gpt-4o' }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
        run: |
          if [ -z "${OPENAI_API_KEY:-}" ]; then
            echo "❌ Missing OPENAI_API_KEY secret. Set it in Settings → Secrets → Actions." >&2
            exit 1
          fi
          # Prefer user-provided IDs; else use discovered
          RAW_IDS="${{ github.event.inputs.ids }}"
          if [ -z "$RAW_IDS" ]; then
            RAW_IDS="${{ steps.discover.outputs.ids }}"
          fi
          TITLE="${{ github.event.inputs.report_title || 'roadmap_report' }}"
          mkdir -p output
          echo "Using IDs: $RAW_IDS"
          bash scripts/generate_report.sh "$RAW_IDS" "prompts/system_multi_id.md" "output/${TITLE}.md"

      - name: Post-process to CSV/JSON (always runs)
        shell: bash
        env:
          TITLE: ${{ github.event.inputs.report_title || 'roadmap_report' }}
          MONTHS: ${{ github.event.inputs.months }}
          SINCE: ${{ github.event.inputs.since }}
          UNTIL: ${{ github.event.inputs.until }}
          INCLUDE: ${{ github.event.inputs.include_instances }}
          EXCLUDE: ${{ github.event.inputs.exclude_instances }}
        run: |
          bash scripts/post_process.sh \
            "output/${TITLE}.md" \
            "output/${TITLE}.csv" \
            "output/${TITLE}.json" \
            "${MONTHS}" "${SINCE}" "${UNTIL}" "${INCLUDE}" "${EXCLUDE}"

      - name: Show output directory (debug)
        shell: bash
        run: |
          echo "Listing output/"
          ls -la output || true

      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-report
          path: |
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.md
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.csv
            output/${{ github.event.inputs.report_title || 'roadmap_report' }}.json
            output/*
          if-no-files-found: warn
