name: Build Microsoft 365 Roadmap Report

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Report title (used in filenames)"
        required: true
        default: "roadmap_report"
      use_graph:
        description: "Use Graph Message Center (needs graph_config.json + cert)"
        required: true
        type: boolean
        default: false
      use_public_scrape:
        description: "Use Playwright public scraping fallback (in addition to RSS fallback)"
        required: true
        type: boolean
        default: true
      public_ids:
        description: "Comma-separated Roadmap IDs for public fallbacks (e.g., 498159,499430)"
        required: false
        default: ""
      months:
        description: "Months back (1..6) for Graph (ignored if 'since' is set)"
        required: false
        default: "3"
      since:
        description: "Since date (YYYY-MM-DD) for Graph (overrides 'months' if set)"
        required: false
        default: ""
      until:
        description: "Until date (kept for compatibility; not used by Graph)"
        required: false
        default: ""
      tenant_cloud:
        description: "Cloud instance label for Graph rows (e.g., Worldwide, GCC, GCC High, DoD)"
        required: false
        default: "Worldwide (Standard Multi-Tenant)"
      skip_generate:
        description: "Skip markdown generation (fetch only)"
        required: true
        type: boolean
        default: false

env:
  PYTHONUNBUFFERED: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps (requirements.txt)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers (only if playwright in requirements.txt AND use_public_scrape)
        if: ${{ (inputs.public_ids != '' || inputs.use_graph == false) && inputs.use_public_scrape == true }}
        run: |
          if grep -q 'playwright' requirements.txt; then
            echo "playwright found in requirements.txt — installing browsers..."
            python -m playwright install --with-deps chromium
          else
            echo "playwright not listed in requirements.txt — skipping browser install."
          fi

      - name: Ensure scripts are executable (if present)
        run: |
          chmod +x scripts/generate_report.sh || true
          chmod +x scripts/post_process.sh || true

      - name: Ensure output dir
        run: mkdir -p output

      - name: Show Graph config presence
        run: |
          if [ -f graph_config.json ]; then
            echo "graph_config.json found."
          else
            echo "graph_config.json NOT found (Graph fetch will fail if use_graph=true)."
          fi

      - name: Fetch rows (Graph primary, public + RSS fallbacks)
        id: fetch_rows
        shell: bash
        env:
          TITLE: ${{ inputs.title }}
          USE_GRAPH: ${{ inputs.use_graph }}
          USE_PUBLIC_SCRAPE: ${{ inputs.use_public_scrape }}
          PUBLIC_IDS: ${{ inputs.public_ids }}
          MONTHS: ${{ inputs.months }}
          SINCE: ${{ inputs.since }}
          TENANT_CLOUD: ${{ inputs.tenant_cloud }}
        run: |
          set -euo pipefail

          CSV_OUT="output/${TITLE}_master.csv"
          JSON_OUT="output/${TITLE}_master.json"
          STATS_OUT="output/${TITLE}_fetch_stats.json"

          GRAPH_FLAG=""
          if [[ "${USE_GRAPH}" != "true" ]]; then
            GRAPH_FLAG="--no-graph"
          fi

          IDS_FLAG=""
          if [[ -n "${PUBLIC_IDS}" ]]; then
            IDS_FLAG="--ids ${PUBLIC_IDS}"
          fi

          PUBLIC_FLAG=""
          if [[ "${USE_PUBLIC_SCRAPE}" != "true" ]]; then
            PUBLIC_FLAG="--no-public-scrape"
          fi

          DATE_FLAGS=""
          if [[ -n "${SINCE}" ]]; then
            DATE_FLAGS="--since ${SINCE}"
          elif [[ -n "${MONTHS}" ]]; then
            DATE_FLAGS="--months ${MONTHS}"
          fi

          echo "Running fetch_messages_graph.py ${GRAPH_FLAG} ${PUBLIC_FLAG} ${IDS_FLAG} ${DATE_FLAGS}"
          python scripts/fetch_messages_graph.py \
            --config graph_config.json \
            ${GRAPH_FLAG} ${PUBLIC_FLAG} ${IDS_FLAG} ${DATE_FLAGS} \
            --tenant-cloud "${TENANT_CLOUD}" \
            --emit csv --out "${CSV_OUT}" \
            --stats-out "${STATS_OUT}" --debug

          python scripts/fetch_messages_graph.py \
            --config graph_config.json \
            ${GRAPH_FLAG} ${PUBLIC_FLAG} ${IDS_FLAG} ${DATE_FLAGS} \
            --tenant-cloud "${TENANT_CLOUD}" \
            --emit json --out "${JSON_OUT}" --debug

          echo "csv=${CSV_OUT}"     >> "$GITHUB_OUTPUT"
          echo "json=${JSON_OUT}"   >> "$GITHUB_OUTPUT"
          echo "stats=${STATS_OUT}" >> "$GITHUB_OUTPUT"

      - name: One-line method summary
        if: ${{ success() }}
        id: method_summary
        shell: bash
        env:
          STATS_PATH: ${{ steps.fetch_rows.outputs.stats }}
        run: |
          set -euo pipefail
          if [[ -f "${STATS_PATH}" ]]; then
            LINE=$(python - <<'PY'
            import json, os
            p=os.environ["STATS_PATH"]
            with open(p, encoding="utf-8") as f:
                s=json.load(f)
            print(f"[rows] Graph={s.get('graph',0)} Public={s.get('public',0)} RSS={s.get('rss',0)} Total={s.get('total',0)}")
            PY
            )
            echo "${LINE}"
            echo "${LINE}" >> "$GITHUB_STEP_SUMMARY"
            echo "summary_line=${LINE}" >> "$GITHUB_OUTPUT"
          else
            echo "No stats file found at ${STATS_PATH}"
          fi

      - name: Derive Roadmap IDs from CSV
        id: ids_from_csv
        if: ${{ success() }}
        shell: bash
        env:
          CSV_PATH: ${{ steps.fetch_rows.outputs.csv }}
        run: |
          set -euo pipefail
          IDS=""
          if [[ -f "${CSV_PATH}" ]]; then
            IDS=$(awk -F, 'NR>1 {print $NF}' "${CSV_PATH}" | \
              grep -oE 'featureid=[0-9]+' | grep -oE '[0-9]+' | sort -u | paste -sd, - || true)
          fi
          echo "Derived IDs: ${IDS}"
          echo "ids=${IDS}" >> "$GITHUB_OUTPUT"

      - name: Generate Markdown (Deep Dive)
        if: ${{ inputs.skip_generate == false && (steps.ids_from_csv.outputs.ids != '' || inputs.public_ids != '') }}
        shell: bash
        env:
          TITLE: ${{ inputs.title }}
          USER_IDS: ${{ inputs.public_ids }}
          DERIVED_IDS: ${{ steps.ids_from_csv.outputs.ids }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
        run: |
          set -euo pipefail
          IDS="${DERIVED_IDS}"
          if [[ -z "${IDS}" && -n "${USER_IDS}" ]]; then
            IDS="${USER_IDS}"
          fi
          echo "Using IDs for Deep Dive: ${IDS}"

          if [[ -z "${OPENAI_API_KEY:-}" ]]; then
            echo "OPENAI_API_KEY not set; skipping generation." >&2
            exit 0
          fi

          bash scripts/generate_report.sh "${IDS}" "prompts/system_multi_id.md" "output/${TITLE}.md"

      - name: Post-process (MD -> CSV/JSON)
        if: ${{ inputs.skip_generate == false }}
        shell: bash
        env:
          TITLE: ${{ inputs.title }}
          MONTHS: ${{ inputs.months }}
          SINCE: ${{ inputs.since }}
          UNTIL: ${{ inputs.until }}
          INCLUDE: ""
          EXCLUDE: ""
        run: |
          set -euo pipefail
          MD="output/${TITLE}.md"
          if [[ -f "${MD}" ]]; then
            echo "Converting ${MD} -> CSV/JSON"
            bash scripts/post_process.sh \
              "output/${TITLE}.md" \
              "output/${TITLE}_from_md.csv" \
              "output/${TITLE}_from_md.json" \
              "${MONTHS}" "${SINCE}" "${UNTIL}" "${INCLUDE}" "${EXCLUDE}"
          else
            echo "No markdown produced; skipping post-process."
          fi

      - name: Upload artifacts (unique name)
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-report-${{ github.run_id }}
          if-no-files-found: warn
          path: |
            output/*.md
            output/*.csv
            output/*.json
