name: Generate Microsoft 365 Roadmap Report

on:
  workflow_dispatch:
    inputs:
      skip_generate:
        description: "Skip API call and use sample output"
        required: false
        default: "true"
      ids:
        description: "Comma-separated roadmap IDs"
        required: false
        default: "498159"
      months:
        description: "Months ahead to include"
        required: false
        default: "3"
      since:
        description: "Start date (YYYY-MM-DD)"
        required: false
        default: ""
      until:
        description: "End date (YYYY-MM-DD)"
        required: false
        default: ""
      include:
        description: "Cloud Instances to include"
        required: false
        default: "GCC"
      exclude:
        description: "Cloud Instances to exclude"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate report
        if: ${{ github.event.inputs.skip_generate != 'true' }}
        run: scripts/generate_report.sh "${{ github.event.inputs.ids }}" prompts/system_multi_id.md output/roadmap_report.md
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}

      - name: Post-process report
        run: scripts/post_process.sh \
          "output/roadmap_report.md" \
          "output/roadmap_report.csv" \
          "output/roadmap_report.json" \
          "${{ github.event.inputs.months }}" \
          "${{ github.event.inputs.since }}" \
          "${{ github.event.inputs.until }}" \
          "${{ github.event.inputs.include }}" \
          "${{ github.event.inputs.exclude }}"
        shell: bash
